const BASE_SERVER_URL = 'http://localhost:50001/api/v1/vendor';
const RUDERALIS_VENDOR_THEME_VARIANT = 'RUDERALIS_VENDOR_THEME_VARIANT';
const RUDERALIS_VENDOR_TOKEN = 'RUDERALIS_VENDOR_TOKEN';
const RUDERALIS_VENDOR_AUTH_DATA = 'RUDERALIS_VENDOR_AUTH_DATA';

export const CONSTANTS = {
    BASE_SERVER_URL,
    RUDERALIS_VENDOR_THEME_VARIANT,
    RUDERALIS_VENDOR_AUTH_DATA,
    RUDERALIS_VENDOR_TOKEN
};